services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=task_message
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1903
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1903
      MYSQL_DATABASE: task_message
      MYSQL_USER: user
      MYSQL_PASSWORD: 1903
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

