name: CI/CD to Docker Hub

on:
  push:
    branches:
      - myTestingBranch  # Запуск на кожен пуш у гілку myTestingBranch

jobs:
  build:
    runs-on: windows-latest  # Запуск на Windows середовищі

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  #  DockerHub Username
        password: ${{ secrets.DOCKERHUB_TOKEN }}     #  DockerHub Token

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-app:latest  #    DockerHub repo (username/repo:tag)

    - name: Run tests
      run: |
        docker build -t php-app .
        docker run php-app vendor/bin/phpunit tests/
